services:
  - type: web
    name: risk-board-game-server
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    healthCheckPath: /
